# SPDX-License-Identifier: GPL-2.0-only

obj-m += ftrace-direct.o
obj-m += ftrace-direct-too.o
obj-m += ftrace-direct-modify.o
obj-m += ftrace-direct-multi.o
obj-m += ftrace-direct-multi-modify.o
obj-m += ftrace-ops.o

CFLAGS_sample-trace-array.o := -I$(src)
obj-m += sample-trace-array.o
