# SPDX-License-Identifier: GPL-2.0-only
obj-m += livepatch-sample.o
obj-m += livepatch-shadow-mod.o
obj-m += livepatch-shadow-fix1.o
obj-m += livepatch-shadow-fix2.o
obj-m += livepatch-callbacks-demo.o
obj-m += livepatch-callbacks-mod.o
obj-m += livepatch-callbacks-busymod.o
