CONFIG_KGDB=y
CONFIG_IKHEADERS=y
CONFIG_KCOV=y
CONFIG_PAGE_OWNER=y
CONFIG_CONFIGFS_FS=y
CONFIG_SECURITYFS=y
CONFIG_FUNCTION_TRACER=y
CONFIG_FTRACE_SYSCALLS=y
CONFIG_LOCK_STAT=y
# CONFIG_RANDOMIZE_BASE is not set
# CONFIG_DRM_I915 is not set
