CONFIG_RUST=y
CONFIG_SAMPLES_RUST=y
CONFIG_SAMPLE_RUST_MINIMAL=m
CONFIG_SAMPLE_RUST_PRINT=m
CONFIG_SAMPLE_RUST_MISC_DEVICE=m
CONFIG_SAMPLE_RUST_DRIVER_PLATFORM=m
CONFIG_SAMPLE_RUST_DRIVER_FAUX=m
CONFIG_SAMPLE_RUST_HELLO=m
CONFIG_SAMPLE_RUST_CHARDEV=m
CONFIG_SAMPLE_RUST_SYNC=m
CONFIG_SAMPLE_RUST_WORKQUEUE=m
CONFIG_SAMPLE_RUST_PROCFS=m
CONFIG_SAMPLE_RUST_LEARN_PLATFORM=m
CONFIG_SAMPLE_RUST_SLAB=m
CONFIG_SAMPLE_RUST_NETDEV=m
