#define HAVE_ERR_H 0
#define HAVE_SYS_EVENTFD_H 1
#define HAVE_SYS_QUEUE_H 1
#define HAVE_SYS_SIGNALFD_H 1
#define HAVE_SYS_TIMERFD_H 1
#define HAVE_SYS_TYPES_H 1

#define HAVE_LINUX_LIMITS_H 1
#define HAVE_LINUX_SOCKIOS_H 1
#define HAVE_LINUX_UNISTD_H 1
#define HAVE_SYSCALL_H 1

#define HAVE_EPOLLRDHUP 1
#define HAVE_NOTE_TRUNCATE 0
#define HAVE_DECL_PPOLL 1
#define HAVE_SYS_PIDFD_OPEN 0
#define HAVE_NOTE_REVOKE 0
