key: "4.19.317"
supported_arches:
  - "x86_64"
  - "arm64"
supported_profiles:
  - "debug"
  - "bpf"
  - "bpf-all"
  - "rust"
  - "rust-all"
  - "samples"
  - "samples-all"
  - "debug-tools"
  - "minimal"
required_profiles: []
default_compat: false
source_url: "https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.19.317.tar.xz"
source_sha256: "062b70cc132378e1c685df44ddf7e05bab4752b690ada17b080655a63f993581"
patch_set: "linux-lab/patches/linux-4.19.317/kernel.patch"
config_family: "modern"
tool_groups:
  - "debug-core"
  - "kernel-tools"
example_groups:
  - "modules-core"
