key: "6.10"
supported_arches:
  - "x86_64"
  - "arm64"
supported_profiles:
  - "debug"
  - "bpf"
  - "bpf-all"
  - "rust"
  - "rust-all"
  - "samples"
  - "samples-all"
  - "debug-tools"
  - "mm-experiments"
  - "minimal"
required_profiles: []
default_compat: false
source_url: "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.10.tar.xz"
source_sha256: "774698422ee54c5f1e704456f37c65c06b51b4e9a8b0866f34580d86fef8e226"
patch_set: "linux-lab/patches/linux-6.10/kernel.patch"
config_family: "modern"
tool_groups:
  - "debug-core"
  - "bpf-core"
  - "kernel-tools"
example_groups:
  - "modules-core"
  - "bpf-core"
