key: "6.18.4"
supported_arches:
  - "x86_64"
  - "arm64"
supported_profiles:
  - "debug"
  - "bpf"
  - "bpf-all"
  - "rust"
  - "rust-all"
  - "samples"
  - "samples-all"
  - "debug-tools"
  - "mm-experiments"
  - "minimal"
  - "fuzzing"
required_profiles: []
default_compat: true
source_url: "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.18.4.tar.xz"
source_sha256: "f850139ca5f79c1bf6bb8b32f92e212aadca97bdaef8a83a7cf4ac4d6a525fab"
patch_set: null
config_family: "modern"
tool_groups:
  - "debug-core"
  - "bpf-core"
  - "kernel-tools"
example_groups:
  - "modules-core"
  - "userspace-core"
  - "rust-core"
  - "bpf-core"
