key: "6.4.3"
supported_arches:
  - "x86_64"
  - "arm64"
supported_profiles:
  - "debug"
  - "bpf"
  - "rust"
  - "samples"
  - "debug-tools"
  - "minimal"
required_profiles: []
default_compat: false
source_url: "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.4.3.tar.xz"
source_sha256: "7134ed29360df6f37a26410630283f0592c91a6d2178a9648226d30ddf8c88a1"
patch_set: "linux-lab/patches/linux-6.4.3/kernel.patch"
config_family: "modern"
tool_groups:
  - "debug-core"
  - "bpf-core"
example_groups:
  - "modules-core"
  - "bpf-core"
