key: "6.9.6"
supported_arches:
  - "x86_64"
  - "arm64"
supported_profiles:
  - "debug"
  - "bpf"
  - "bpf-all"
  - "rust"
  - "rust-all"
  - "samples"
  - "samples-all"
  - "debug-tools"
  - "mm-experiments"
  - "minimal"
  - "fuzzing"
required_profiles: []
default_compat: false
source_url: "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.9.6.tar.xz"
source_sha256: "5d4366e2b89998f274abe03557ef3bc78b58e47fc62c102d51e6f49e5ed96b4b"
patch_set: "linux-lab/patches/linux-6.9.6/kernel.patch"
config_family: "modern"
tool_groups:
  - "debug-core"
  - "bpf-core"
  - "kernel-tools"
example_groups:
  - "modules-core"
  - "bpf-core"
